### ISSUE TITLE
use it only on ros2

### ISSUE THREAD

**Issue by vpegasus** [antonikaras/thesis_ros2#2]
hi, thanks for your good sharing project
I am a new guy on ROS, I wonder,  can I use this project only on ROS2 for learning robot autonomous exploration? 
as I read the readme file, I find tboth ros and ros2 may be needed

**Comment by antonikaras** [comment]
ROS is needed only to display data in Unity otherwise it's not necessary. The autonomous exploration part is developed in ROS2 so you can use it without installing ROS.
